{- *** MOCS-COPYRIGHT-NOTICE-BEGIN ***
 -
 - This copyright notice is auto-generated by ./add-copyright-notice.
 - Additional copyright notices must be added below the last line of this notice.
 -
 - MoCS (https://lewis.cs.uni-saarland.de/tools/mocs/): "test/RolloutStat.hs".
 - The content of this file is copyright of Saarland University -
 - Copyright (C) 2009 Saarland University, Reactive Systems Group, Lars Kuhtz <kuhtz@cs.uni-sb.de>.
 -
 - This file is part of MoCS (https://lewis.cs.uni-saarland.de/tools/mocs/).
 -
 - License: three-clause BSD style license.
 - The license text can be found in the file LICENSE.
 -
 - *** MOCS-COPYRIGHT-NOTICE-END *** -}

-- plot: echo "plot 'data.gplot'" | gnuplot -persist
module Main where

import Debug.Trace

import Control.Monad
  
import Data.List
-- import qualified Data.Map as M

import IO

import PSL
import T2Automaton

import CExpr
import CAut

main = do

  -- Parse Formula
  s <- getLine
  f <- either (error . show) (return) (parsePSL s)

  -- Get steps
  i <- read `liftM` getLine

  -- Automaton
  (_,_,a) <- createAut f
  -- putStrLn $ "automaton:"
  -- putStrLn $ toString $ ptable
  
  autToDot "aut" a "automaton"
  -- sctx <- contextSize ctx
  -- putStrLn $ "size of context: " ++ (show sctx)
 
  mapM (rsize a) [0..i]

  where
  rsize a x = trace (show x) $ do 
    e <- autPrefixRollout (fromInteger x) a
    se <- exprSize e
    putStrLn $ show x ++ " " ++ show se
    
