-- *** MOCS-COPYRIGHT-NOTICE-BEGIN ***
--
-- This copyright notice is auto-generated by ./add-copyright-notice.
-- Additional copyright notices must be added below the last line of this notice.
--
-- MoCS (https://lewis.cs.uni-saarland.de/tools/mocs/): "vhdl/d.vhdl".
-- The content of this file is copyright of Saarland University -
-- Copyright (C) 2009 Saarland University, Reactive Systems Group, Lars Kuhtz.
--
-- This file is part of MoCS (https://lewis.cs.uni-saarland.de/tools/mocs/).
--
-- License: three-clause BSD style license.
-- The license text can be found in the file LICENSE.
--
-- *** MOCS-COPYRIGHT-NOTICE-END ***

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

-- A very simple D-flip-flop (I hope)

entity dff is 
    Port (CLOCK : in STD_LOGIC;
          input : in STD_LOGIC;
          output: out STD_LOGIC := '0');
end dff;

architecture Behavioral of dff is

begin
    process (CLOCK)
    begin
        if (CLOCK'event and CLOCK='1') then
            output <= input;
        end if;
    end process;

end Behavioral;

