-- *** MOCS-COPYRIGHT-NOTICE-BEGIN ***
--
-- This copyright notice is auto-generated by ./add-copyright-notice.
-- Additional copyright notices must be added below the last line of this notice.
--
-- MoCS (https://lewis.cs.uni-saarland.de/tools/mocs/): "vhdl/d_tb.vhdl".
-- The content of this file is copyright of Saarland University -
-- Copyright (C) 2009 Saarland University, Reactive Systems Group, Lars Kuhtz.
--
-- This file is part of MoCS (https://lewis.cs.uni-saarland.de/tools/mocs/).
--
-- License: three-clause BSD style license.
-- The license text can be found in the file LICENSE.
--
-- *** MOCS-COPYRIGHT-NOTICE-END ***

-- -----------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use work.dff;

entity dff_tb is
end dff_tb;

architecture Behavioral of dff_tb is

    signal CLOCK, i, o : STD_LOGIC;
    signal t0, t1 : STD_LOGIC;

begin

    dff0 : entity work.dff(Behavioral)
    port map (CLOCK, i, t0);

    dff1 : entity work.dff(Behavioral)
    port map (CLOCK, t0, t1);

    dff2 : entity work.dff(Behavioral)
    port map (CLOCK, t1, o);

    process
    begin 
        CLOCK <= '1'; wait for 5 ns;
        CLOCK <= '0'; wait for 5 ns;
    end process;
    
    process
    begin
        i <= '0'; wait for 8 ns;
        i <= '1'; wait for 11 ns;
        i <= '0'; wait for 13 ns;
        i <= '1'; wait for 3 ns;
        wait;
    end process;
end Behavioral;

