-- *** MOCS-COPYRIGHT-NOTICE-BEGIN ***
--
-- This copyright notice is auto-generated by ./add-copyright-notice.
-- Additional copyright notices must be added below the last line of this notice.
--
-- MoCS (https://lewis.cs.uni-saarland.de/tools/mocs/): "vhdl/pipeline.vhdl".
-- The content of this file is copyright of Saarland University -
-- Copyright (C) 2009 Saarland University, Reactive Systems Group, Lars Kuhtz.
--
-- This file is part of MoCS (https://lewis.cs.uni-saarland.de/tools/mocs/).
--
-- License: three-clause BSD style license.
-- The license text can be found in the file LICENSE.
--
-- *** MOCS-COPYRIGHT-NOTICE-END ***

-- ----------------------------------------------------------------- --
-- use work.general.all;
library IEEE;
use IEEE.STD_LOGIC_1164.all;
use IEEE.numeric_std.all;

-- the pipeline for a single prop
entity pipeline is
    generic (LENGTH : integer := 32);
    Port (CLOCK : in STD_LOGIC;
          input : in STD_LOGIC;
          output : out unsigned(LENGTH downto 0));
end pipeline;


architecture Behavioral of pipeline is

    signal tmp : unsigned(LENGTH - 1 downto 0);
  
begin

    process (CLOCK)
    begin
        if (CLOCK'event and CLOCK='1') then
            if (LENGTH > 1) then
                tmp <= tmp(LENGTH - 2 downto 0) & input;
            elsif (LENGTH = 1) then
                tmp <= "" & input;
            end if;
        end if;
    end process;
   
    output <= tmp & input;

end Behavioral;

