#!/bin/bash

# *** MOCS-COPYRIGHT-NOTICE-BEGIN ***
#
# This copyright notice is auto-generated by ./add-copyright-notice.
# Additional copyright notices must be added below the last line of this notice.
#
# MoCS (https://lewis.cs.uni-saarland.de/tools/mocs/): "formulas/cir-size.sh".
# The content of this file is copyright of Saarland University -
# Copyright (C) 2009 Saarland University, Reactive Systems Group, Lars Kuhtz.
#
# This file is part of MoCS (https://lewis.cs.uni-saarland.de/tools/mocs/).
#
# License: three-clause BSD style license.
# The license text can be found in the file LICENSE.
#
# *** MOCS-COPYRIGHT-NOTICE-END ***

if [[ $# -lt 1 ]] ; then
    echo "Usage: $0 [-n|-l|-f|-s] <file-name>"
    exit 1
elif [[ $# = 1 ]] ; then
    OPT=""
    ARG=$1
else
    OPT=$1
    ARG=$2
fi

S=`grep '^ *\<signal\> \+\<\w\+\> : \<STD_LOGIC\>; *$' $ARG | wc -l`
LG=`grep '^ *\<\w\+\> <= \<\w\+\> \<\(and\|or\)\> \<\w\+\> *; *$' $ARG | wc -l`
D=`grep 'entity work.dff' $ARG | wc -l`

case $OPT in
-n) echo "$LG $D $S";;
-l) echo "$LG";;
-f) echo "$D";;
-s) echo "$S";;
*) echo "logic gates: $LG, flip-flops: $D, signals: $S";;
esac
