#!/bin/bash

# *** MOCS-COPYRIGHT-NOTICE-BEGIN ***
#
# This copyright notice is auto-generated by ./add-copyright-notice.
# Additional copyright notices must be added below the last line of this notice.
#
# MoCS (https://lewis.cs.uni-saarland.de/tools/mocs/): "formulas/plot12.sh".
# The content of this file is copyright of Saarland University -
# Copyright (C) 2009 Saarland University, Reactive Systems Group, Lars Kuhtz <kuhtz@cs.uni-sb.de>.
#
# This file is part of MoCS (https://lewis.cs.uni-saarland.de/tools/mocs/).
#
# License: three-clause BSD style license.
# The license text can be found in the file LICENSE.
#
# *** MOCS-COPYRIGHT-NOTICE-END ***

for ((i=1;i<=$1;++i)) ; do 
    ./runall12.sh $(($i*3)) $(($i*2)) $(($i*1)) |
    cut -d ' ' -f '5' |
    sed 's/:\|,//g' |
    gawk -v i=$i 'BEGIN {x=""}; {x=x " " $1}; END {print i x}' ; 
done > tmp
rm -f data
for ((i=2;i<=13;++i)) ; do 
    cat tmp |
    cut -d ' ' -f "1,$i" >> data ;
    echo -e "\n" >> data; 
done


gnuplot  -persist <(echo "plot 'data', x**3, x**3.3")

