#!/bin/bash

# *** MOCS-COPYRIGHT-NOTICE-BEGIN ***
#
# This copyright notice is auto-generated by ./add-copyright-notice.
# Additional copyright notices must be added below the last line of this notice.
#
# MoCS (https://lewis.cs.uni-saarland.de/tools/mocs/): "formulas/set-bounds.sh".
# The content of this file is copyright of Saarland University -
# Copyright (C) 2009 Saarland University, Reactive Systems Group, Lars Kuhtz.
#
# This file is part of MoCS (https://lewis.cs.uni-saarland.de/tools/mocs/).
#
# License: three-clause BSD style license.
# The license text can be found in the file LICENSE.
#
# *** MOCS-COPYRIGHT-NOTICE-END ***

if [[ $# = 0 ]] ; then
  sed -e "s/\\\\b/(infty)/g; s/\\\\m/(infty)/g; s/\\\\s/(infty)/g"
elif [[ $# = 1 ]] ; then
  sed -e "s/\\\\b/(3*$1)/g; s/\\\\m/(2*$1)/g; s/\\\\s/$1/g"
elif [[ $# = 3 ]] ; then
  sed -e "s/\\\\b/$1/g; s/\\\\m/$2/g; s/\\\\s/$3/g"
else
    echo "Error: wrong number of arguments" 1>&2
    echo "Usage: $0             (set bounds to infty)" 1>&2
    echo "       $0 n           (set bounds to 3*n, 2*n, n, respectively)" 1>&2
    echo "       $0 n0 n1 n2    (set bounds to n0, n1, n2 respectively)" 1>&2
    exit 1
fi

