#!/bin/bash

# *** MOCS-COPYRIGHT-NOTICE-BEGIN ***
#
# This copyright notice is auto-generated by ./add-copyright-notice.
# Additional copyright notices must be added below the last line of this notice.
#
# MoCS (https://lewis.cs.uni-saarland.de/tools/mocs/): "formulas/vardigen.sh".
# The content of this file is copyright of Saarland University -
# Copyright (C) 2009 Saarland University, Reactive Systems Group, Lars Kuhtz.
#
# This file is part of MoCS (https://lewis.cs.uni-saarland.de/tools/mocs/).
#
# License: three-clause BSD style license.
# The license text can be found in the file LICENSE.
#
# *** MOCS-COPYRIGHT-NOTICE-END ***

#echo "\G ( (\not (\BN (\s) (x \and (\N (\BG (\s - 1) \not x))))) \or"
#echo "     (\BF (\s - 1) ("
#echo "              (\not i1 \or (\BF (\s) (i1 \and (x \and (\N (\BG (\s - 1) \not x))))))"
#for ((i=0; i<=$1; ++i)) do
#  echo "        \and  (\not i$i \or (\BF (\s) (i$i \and (x \and (\N (\BG (\s - 1) \not x))))))"
#done
#echo "      ))"
#echo "   )"

echo "\F ( \not x "
for ((i=0; i<=$1; ++i)) do 
    echo "\and (i$i \equiv \BF (\s) (i$i \and x) )"
done
echo ") \and \G (x \implies \N \G \not x) \and \F x"

