/* *** MOCS-COPYRIGHT-NOTICE-BEGIN ***
 *
 * This copyright notice is auto-generated by ./add-copyright-notice.
 * Additional copyright notices must be added below the last line of this notice.
 *
 * MoCS (https://lewis.cs.uni-saarland.de/tools/mocs/): "c-bindings/sm.h".
 * The content of this file is copyright of Saarland University -
 * Copyright (C) 2009 Saarland University, Reactive Systems Group, Lars Kuhtz.
 *
 * This file is part of MoCS (https://lewis.cs.uni-saarland.de/tools/mocs/).
 *
 * License: three-clause BSD style license.
 * The license text can be found in the file LICENSE.
 *
 * *** MOCS-COPYRIGHT-NOTICE-END *** */

#ifndef _SM_H_
#define _SM_H_

#include "context.h"
#include "expr.h"
#include "aa.h"

#ifdef __cplusplus
extern "C" {
#endif

// incomplete. Pure pointer-interface.
struct state_machine_t;
typedef struct state_machine_t* state_machine_ptr;

// constructors/ destructors
state_machine_ptr mk_state_machine(automaton_ptr a);
void free_state_machine(state_machine_ptr a);

// Get Context
context_ptr get_sm_context(state_machine_ptr a);

// pretty-printing
void state_machine2dot(const char* file_name, const state_machine_ptr a, const char* name);

#ifdef __cplusplus
}
#endif

#endif // _SM_H_

